"""add damage min max

Revision ID: 0140533bb2bf
Revises: fe2b8325a38a
Create Date: 2021-11-07 21:56:39.925569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0140533bb2bf'
down_revision = 'fe2b8325a38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('min_dmg', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('max_dmg', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('strength', sa.Integer(), nullable=True))
    op.drop_column('player', 'attack')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('attack', sa.INTEGER(), nullable=True))
    op.drop_column('player', 'strength')
    op.drop_column('player', 'max_dmg')
    op.drop_column('player', 'min_dmg')
    # ### end Alembic commands ###
