"""add stat_point to player

Revision ID: 0abfdd4472b9
Revises: 2ba92da42b86
Create Date: 2021-11-04 20:27:04.102359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abfdd4472b9'
down_revision = '2ba92da42b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('stat_point', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'stat_point')
    # ### end Alembic commands ###
