"""weapon min max dmg

Revision ID: 15b17f3e0e63
Revises: 027b42591253
Create Date: 2021-11-08 20:31:25.296207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b17f3e0e63'
down_revision = '027b42591253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enemy', sa.Column('min_dmg', sa.Integer(), nullable=True))
    op.add_column('enemy', sa.Column('max_dmg', sa.Integer(), nullable=True))
    op.drop_column('enemy', 'attack')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enemy', sa.Column('attack', sa.INTEGER(), nullable=True))
    op.drop_column('enemy', 'max_dmg')
    op.drop_column('enemy', 'min_dmg')
    # ### end Alembic commands ###
