"""potion desc

Revision ID: 1819cbdf8379
Revises: 183a752dc596
Create Date: 2021-11-11 16:50:10.915961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1819cbdf8379'
down_revision = '183a752dc596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('potion', sa.Column('description', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('potion', 'description')
    # ### end Alembic commands ###
