"""items add stats

Revision ID: 183a752dc596
Revises: 15b17f3e0e63
Create Date: 2021-11-08 20:47:47.986983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183a752dc596'
down_revision = '15b17f3e0e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armor', sa.Column('vitality', sa.Integer(), nullable=True))
    op.add_column('boots', sa.Column('dexterity', sa.Integer(), nullable=True))
    op.add_column('helmet', sa.Column('vitality', sa.Integer(), nullable=True))
    op.add_column('shield', sa.Column('charisma', sa.Integer(), nullable=True))
    op.add_column('weapon', sa.Column('charisma', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon', 'charisma')
    op.drop_column('shield', 'charisma')
    op.drop_column('helmet', 'vitality')
    op.drop_column('boots', 'dexterity')
    op.drop_column('armor', 'vitality')
    # ### end Alembic commands ###
