"""potion heal nullable true

Revision ID: 74d48d5d9582
Revises: 183a752dc596
Create Date: 2021-11-11 16:46:17.408827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d48d5d9582'
down_revision = '183a752dc596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('potion', 'heal',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('potion', 'heal',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
