"""player double exp

Revision ID: ad3fad76e42f
Revises: 1819cbdf8379
Create Date: 2021-11-11 17:41:42.336071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3fad76e42f'
down_revision = '1819cbdf8379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('double_exp', sa.Integer(), nullable=True))
    op.drop_column('player', 'dungeon_points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('dungeon_points', sa.INTEGER(), nullable=True))
    op.drop_column('player', 'double_exp')
    # ### end Alembic commands ###
