"""add charisma

Revision ID: ca804f2cb47a
Revises: 5666aef1f2fb
Create Date: 2021-11-06 21:41:09.740289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca804f2cb47a'
down_revision = '5666aef1f2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('charisma', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'charisma')
    # ### end Alembic commands ###
