"""add strength cost

Revision ID: d105a83c45b0
Revises: 0140533bb2bf
Create Date: 2021-11-07 22:15:46.037692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd105a83c45b0'
down_revision = '0140533bb2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('strength_cost', sa.Integer(), nullable=True))
    op.drop_column('player', 'attack_cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('attack_cost', sa.INTEGER(), nullable=True))
    op.drop_column('player', 'strength_cost')
    # ### end Alembic commands ###
