"""add charisma and charisma cost

Revision ID: fe2b8325a38a
Revises: ca804f2cb47a
Create Date: 2021-11-07 19:28:08.922449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2b8325a38a'
down_revision = 'ca804f2cb47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('charisma_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'charisma_cost')
    # ### end Alembic commands ###
